
default_stages: [pre-commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: ['--unsafe']
  - id: check-added-large-files
  - id: detect-private-key
  - id: check-json
  - id: check-merge-conflict

- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
  - id: terraform-docs-system
    name: Check correct docs are generated for our readme
    files: ./Module-8/readme.md
    args: [".", "--output-check"]
    pass_filenames: False

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0
  hooks:
  - id: terraform_fmt
    args:
    - --args=-check
    - --args=-recursive
  - id: terraform_validate
    args:
      - --tf-init-args=-upgrade
  - id: terraform_tfsec
  - id: terraform_tflint
